"""add product_categories relation

Revision ID: 6fce463e240b
Revises: 21898ac088bf
Create Date: 2025-08-27 14:55:51.617818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fce463e240b'
down_revision: Union[str, None] = '21898ac088bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('colors', 'hex',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('uq_colors_name_lower'), table_name='colors')
    op.alter_column('product_color_images', 'sort',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_product_color'), table_name='product_color_images')
    op.alter_column('product_images', 'sort',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('product_variants', 'color_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('product_variants', 'size_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('product_variants', 'sku',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('uq_variant_color_when_no_size'), table_name='product_variants', postgresql_where='(size_id IS NULL)')
    op.drop_constraint(op.f('uq_variant_combo'), 'product_variants', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_variant_combo'), 'product_variants', ['product_id', 'color_id', 'size_id'])
    op.create_index(op.f('uq_variant_color_when_no_size'), 'product_variants', ['product_id', 'color_id'], unique=True, postgresql_where='(size_id IS NULL)')
    op.alter_column('product_variants', 'sku',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('product_variants', 'size_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('product_variants', 'color_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('product_images', 'sort',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('idx_product_color'), 'product_color_images', ['product_id', 'color_id'], unique=False)
    op.alter_column('product_color_images', 'sort',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('uq_colors_name_lower'), 'colors', [sa.literal_column('lower(name)')], unique=True)
    op.alter_column('colors', 'hex',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
