"""add user_id to products

Revision ID: bde63b5b4bd4
Revises: 1767c2fb40b1
Create Date: 2025-08-27 20:34:06.348605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bde63b5b4bd4'
down_revision: Union[str, None] = '1767c2fb40b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column('products', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(
        'fk_products_user_id_users',
        'products',
        'users',
        ['user_id'],
        ['id'],
        ondelete='CASCADE'
    )


def downgrade():
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
